// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: isearch.proto

package isearch

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ISearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phrase        string                 `protobuf:"bytes,1,opt,name=phrase,proto3" json:"phrase,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ISearchRequest) Reset() {
	*x = ISearchRequest{}
	mi := &file_isearch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ISearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ISearchRequest) ProtoMessage() {}

func (x *ISearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_isearch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ISearchRequest.ProtoReflect.Descriptor instead.
func (*ISearchRequest) Descriptor() ([]byte, []int) {
	return file_isearch_proto_rawDescGZIP(), []int{0}
}

func (x *ISearchRequest) GetPhrase() string {
	if x != nil {
		return x.Phrase
	}
	return ""
}

func (x *ISearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type Comics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Comics) Reset() {
	*x = Comics{}
	mi := &file_isearch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Comics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comics) ProtoMessage() {}

func (x *Comics) ProtoReflect() protoreflect.Message {
	mi := &file_isearch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comics.ProtoReflect.Descriptor instead.
func (*Comics) Descriptor() ([]byte, []int) {
	return file_isearch_proto_rawDescGZIP(), []int{1}
}

func (x *Comics) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Comics) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ISearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comics        []*Comics              `protobuf:"bytes,1,rep,name=comics,proto3" json:"comics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ISearchResponse) Reset() {
	*x = ISearchResponse{}
	mi := &file_isearch_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ISearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ISearchResponse) ProtoMessage() {}

func (x *ISearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_isearch_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ISearchResponse.ProtoReflect.Descriptor instead.
func (*ISearchResponse) Descriptor() ([]byte, []int) {
	return file_isearch_proto_rawDescGZIP(), []int{2}
}

func (x *ISearchResponse) GetComics() []*Comics {
	if x != nil {
		return x.Comics
	}
	return nil
}

var File_isearch_proto protoreflect.FileDescriptor

const file_isearch_proto_rawDesc = "" +
	"\n" +
	"\risearch.proto\x12\aisearch\x1a\x1bgoogle/protobuf/empty.proto\">\n" +
	"\x0eISearchRequest\x12\x16\n" +
	"\x06phrase\x18\x01 \x01(\tR\x06phrase\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"*\n" +
	"\x06Comics\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\":\n" +
	"\x0fISearchResponse\x12'\n" +
	"\x06comics\x18\x01 \x03(\v2\x0f.isearch.ComicsR\x06comics2\x83\x01\n" +
	"\aISearch\x128\n" +
	"\x04Ping\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x12>\n" +
	"\aISearch\x12\x17.isearch.ISearchRequest\x1a\x18.isearch.ISearchResponse\"\x00B Z\x1eyadro.com/course/proto/isearchb\x06proto3"

var (
	file_isearch_proto_rawDescOnce sync.Once
	file_isearch_proto_rawDescData []byte
)

func file_isearch_proto_rawDescGZIP() []byte {
	file_isearch_proto_rawDescOnce.Do(func() {
		file_isearch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_isearch_proto_rawDesc), len(file_isearch_proto_rawDesc)))
	})
	return file_isearch_proto_rawDescData
}

var file_isearch_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_isearch_proto_goTypes = []any{
	(*ISearchRequest)(nil),  // 0: isearch.ISearchRequest
	(*Comics)(nil),          // 1: isearch.Comics
	(*ISearchResponse)(nil), // 2: isearch.ISearchResponse
	(*emptypb.Empty)(nil),   // 3: google.protobuf.Empty
}
var file_isearch_proto_depIdxs = []int32{
	1, // 0: isearch.ISearchResponse.comics:type_name -> isearch.Comics
	3, // 1: isearch.ISearch.Ping:input_type -> google.protobuf.Empty
	0, // 2: isearch.ISearch.ISearch:input_type -> isearch.ISearchRequest
	3, // 3: isearch.ISearch.Ping:output_type -> google.protobuf.Empty
	2, // 4: isearch.ISearch.ISearch:output_type -> isearch.ISearchResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_isearch_proto_init() }
func file_isearch_proto_init() {
	if File_isearch_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_isearch_proto_rawDesc), len(file_isearch_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_isearch_proto_goTypes,
		DependencyIndexes: file_isearch_proto_depIdxs,
		MessageInfos:      file_isearch_proto_msgTypes,
	}.Build()
	File_isearch_proto = out.File
	file_isearch_proto_goTypes = nil
	file_isearch_proto_depIdxs = nil
}
